name = "morningside-decapsso"
main = "src/index.js"
compatibility_date = "2024-10-01"

[vars]
GITHUB_CLIENT_ID="Ov23liJpWi0bkkzweeHs"
GITHUB_CLIENT_SECRET= "4aa5867ec18714db8730d7ba4f2a28e9aa4b01d2"


